### ISSUE TITLE
AttributeError: 'thread._local' object has no attribute 'firefox'

### ISSUE THREAD

**Issue by medwards** [salad/salad#1]
When I execute lettuce a firefox window opens with a 'webdriver' not in the status bar at the bottom. However nothing happens, eventually the window closes and the following backtrace is produced:

```
salad - WARNING - Django terrains not imported.
salad - WARNING - Django steps not imported.
salad - WARNING - Error starting up firefox
Traceback (most recent call last):
  File "/home/medwards/.virtualenvs/core_frontend_demo/local/lib/python2.7/site-packages/lettuce/registry.py", line 85, in call_hook
    callback(*args, **kw)
  File "/home/medwards/.virtualenvs/core_frontend_demo/local/lib/python2.7/site-packages/salad/terrains/browser.py", line 7, in setup_browser
    world.browser = world.firefox
AttributeError: 'thread._local' object has no attribute 'firefox'
```

My features folder contains the following feature test

```
Feature: Ensuring that Item List works
In order to make sure Item List works
As a client
I open the Item List

Scenario: Opening the Item List works
        Given I visit the url "http://localhost:5000/search/"
        When I look around
        Then I should see "Testitem" somewhere in the page
```

Not sure what I'm missing at this point :/

**Comment by schmilblick** [comment]
Adding a comment since I had this error and managed to solve it for my special case.

It wasn't an issue with salad, it was a wrong parameter to pyvirtualdisplay.display.Display (in my case, visible=1 instead of visible=False). If visible is evaluated as True, xephyr is used instead of xvfb. Since I was running firefox headless in a VM without xephyr or any X server running it resulted in this error (the FirefoxBinary logged the error: Cannot connect to display or something similar).
